### ISSUE TITLE
Report of some bugs that have had dealt with it  or could not deal with.

### ISSUE THREAD

**Issue by NaughtDZ** [andreae293/Dreambooth-Stable-Diffusion-cpu#1]
1. 
File "J:\Dreambooth-Stable-Diffusion-cpu\main.py", line 18, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
**ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed'** 
--------------
According to "https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/4111"
The function was moved to a new script with a different name . Try to import it as :

**from pytorch_lightning.utilities.rank_zero import rank_zero_only**

And
  File "J:\Dreambooth-Stable-Diffusion-cpu\ldm\models\diffusion\ddpm.py", line 21, in <module>
Has same issue.

*******************************

2.
Traceback (most recent call last):
  File "J:\Dreambooth-Stable-Diffusion-cpu\main.py", line 851, in <module>
    if trainer.global_rank == 0:
**NameError: name 'trainer' is not defined. Did you mean: 'Trainer'?**
-------------------
I just **change trainer to Traniner**,and program can running,but dont know if have other issues.

**********************************

3.
Traceback (most recent call last):
  File "J:\Dreambooth-Stable-Diffusion-cpu\main.py", line 670, in <module>
    trainer_kwargs["logger"] = instantiate_from_config(logger_cfg)
  File "J:\Dreambooth-Stable-Diffusion-cpu\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "J:\Dreambooth-Stable-Diffusion-cpu\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
AttributeError: module 'pytorch_lightning.loggers' has no attribute 'TestTubeLogger'. Did you mean: 'NeptuneLogger'?
------------
thx:[78Alpha](https://github.com/78Alpha)
> Replace all instances of TestTubeLogger with CSVLogger

**Comment by 78Alpha** [comment]
Replace all instances of TestTubeLogger with CSVLogger

**Comment by 78Alpha** [comment]
After altering all the necessary parts it will auto Kill after 1 epoch, so it seems to hit a wall.

`Epoch 0:   0%| | 1/1010 [00:40<11:16:58, 40.26s/it, loss=0.625, v_num=0, train/loss_simple_step=0.604, train/loss_vlb_st
Killed`

**Comment by NaughtDZ** [comment]
New issue:
4.
Traceback (most recent call last):
  File "J:\Dreambooth-Stable-Diffusion-cpu\main.py", line 830, in <module>
    trainer.fit(model, data)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 579, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 621, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 984, in _run
    verify_loop_configurations(self)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py", line 53, in verify_loop_configurations
    _check_deprecated_callback_hooks(trainer)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py", line 266, in _check_deprecated_callback_hooks
    raise RuntimeError(
RuntimeError: The `Callback.on_pretrain_routine_start` hook was removed in v1.8. Please use `Callback.on_fit_start` instead.
--------------------------------

thx:[78Alpha](https://github.com/78Alpha)

> Main.py, line 327 rename on_pretrain_routine_start to **on_fit_start** or **on_fit_end**

**Comment by 78Alpha** [comment]
Main.py, line 327 or 330, rename on_pretrain_routine_start to on_fit_start or on_fit_end

**Comment by andreae293** [comment]
Regarding error.3 
`AttributeError: module 'pytorch_lightning.loggers' has no attribute 'TestTubeLogger'`

did you guys install test-tube?
`pip install test-tube`

**Comment by NaughtDZ** [comment]
> 

yes it working ,thx

**Comment by NaughtDZ** [comment]
New issue 5.
----------
Epoch 0:   0%|                                                                                | 0/2020 [00:00<?, ?it/s]Summoning checkpoint.
Traceback (most recent call last):
  File "J:\Dreambooth-Stable-Diffusion-cpu\main.py", line 830, in <module>
    trainer.fit(model, data)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 579, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 621, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1058, in _run
    results = self._run_stage()
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1137, in _run_stage
    self._run_train()
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1160, in _run_train
    self.fit_loop.run()
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 205, in advance
    response = self.trainer._call_lightning_module_hook("on_train_batch_start", batch, batch_idx)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1302, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\lightning_utilities\core\rank_zero.py", line 24, in wrapped_fn
    return fn(*args, **kwargs)
  File "C:\Users\Naught\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: LatentDiffusion.on_train_batch_start() missing 1 required positional argument: 'dataloader_idx'
Epoch 0:   0%|          | 0/2020 [00:52<?, ?it/s]

--------------------

**Not solved yet.Googleing...................**

**Comment by andreae293** [comment]
i think you are starting from a messy environment
probably the correct packages are not installed

This is what i did just a moment ago on a fresh new windows installation with 32GB RAM:
-install anaconda3
-install git on windows from [there](https://git-scm.com/download/win)
-add git executable path to environment variables (on my pc located on C:\Program Files\Git\bin )

-download this repo somewhere on your pc
-place model.ckpt in the right folder
-create regularization and training folder and put images there

-open anaconda prompt and navigate to this repo 
```
cd Dreambooth-Stable-Diffusion-cpu-main
conda env create -f environment.yaml
conda activate ldm
python main.py --base configs/stable-diffusion/v1-finetune_unfrozen.yaml -t --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt -n dog_testing  --data_root ./training/ --reg_data_root ./regularization --class_word dog --logdir ./logs/

```
and its working
![img](https://user-images.githubusercontent.com/111545141/200339310-fa87b120-dbe7-43b6-9fec-7635d43f7678.png)

be advsided that 32GB are not enough and you will get memory error
reserve something like 10GB or more for virtual ram

edit: also check that
`conda env create -f environment.yaml`
does not return an error

**Comment by 78Alpha** [comment]
We were both trying to run from a newer environment. However, it involves manually editing a lot of things to get it "working".

Even altering the site packages themselves.

**Comment by cyruschan360** [comment]
> i think you are starting from a messy environment probably the correct packages are not installed
> 
> This is what i did just a moment ago on a fresh new windows installation with 32GB RAM: -install anaconda3 -install git on windows from [there](https://git-scm.com/download/win) -add git executable path to environment variables (on my pc located on C:\Program Files\Git\bin )
> 
> -download this repo somewhere on your pc -place model.ckpt in the right folder -create regularization and training folder and put images there
> 
> -open anaconda prompt and navigate to this repo
> 
> ```
> cd Dreambooth-Stable-Diffusion-cpu-main
> conda env create -f environment.yaml
> conda activate ldm
> python main.py --base configs/stable-diffusion/v1-finetune_unfrozen.yaml -t --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt -n dog_testing  --data_root ./training/ --reg_data_root ./regularization --class_word dog --logdir ./logs/
> ```
> 
> and its working ![img](https://user-images.githubusercontent.com/111545141/200339310-fa87b120-dbe7-43b6-9fec-7635d43f7678.png)
> 
> be advsided that 32GB are not enough and you will get memory error reserve something like 10GB or more for virtual ram
> 
> edit: also check that `conda env create -f environment.yaml` does not return an error

Thank you so much! After destroying the old conda enviroment and recreate a new environment with 
`conda env create -f environment.yaml`, everything works like a charm!

Apparently, new version of depending libraries are causing trouble, e.g. `conda install -c conda-forge python` now provides 3.11.0 which breaks pytorch. The trick is sticking with the versions in environment.yaml strictly.

**Comment by andreae293** [comment]
> We were both trying to run from a newer environment. However, it involves manually editing a lot of things to get it "working".
> 
> Even altering the site packages themselves.

@78Alpha
unfortunately i too ran in this kind of problems all the time when using any ML-related project
i am under the impression that those environments breaks really easily: installing a different version of a package, even an updated one can break the environment.
all i can suggest you is to clean the old anaconda environment, even manually deleting the "ldm" environment folder and recreate it with the steps i wrote

@cyruschan360
im glad that its working for you
did you have to reserve any memory to virtual RAM?

**Comment by 78Alpha** [comment]
@NaughtDZ 

`TypeError: LatentDiffusion.on_train_batch_start() missing 1 required positional argument: 'dataloader_idx'`

main.py, ~456, on_train_batch_end
`    def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx, dataloader_idx=0):`
and ddpm.py ~509 on_train_batch_start
`    def on_train_batch_start(self, batch, batch_idx, dataloader_idx=0):`

They are set to 0 because it doesn't even use those to begin with as far as I can tell, but I keep them in just in case.

**Comment by 78Alpha** [comment]
@andreae293 

Seems to be a linux thing, as @NaughtDZ got the Automatic1111 extension working on CPU by the looks
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/4386

Also referenced https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2002#issuecomment-1273479365
Seems to always kill after 1 step no matter what in WSL2 at least

But native windows worked fine
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2002#issuecomment-1273668196

**Comment by andreae293** [comment]
that pull request looks like it has an even faster cpu training than this repo (33s/it vs 50s/it), i'm going to give it a try

**Comment by 78Alpha** [comment]
The speed varies, I am running at fastest 47s/it on a Ryzen 7 3700x, but it does work, no doubt. Model saving still has some issues but that can be done after.

**Comment by andreae293** [comment]
47s/it on this repo or automatic111 webui?

**Comment by 78Alpha** [comment]
@andreae293 The webui implementation by D8ahazard. After turning off the train text encoder (lower quality output). 54-58s/it if left on.

**Comment by NaughtDZ** [comment]
> 47s/it on this repo or automatic111 webui?

I got almost 50s/it on this repo wtih my 5800X ,and it It only takes 60% around of my CPU, and 32G memory is not fully used.
![image](https://user-images.githubusercontent.com/37768911/200476845-703be55a-ac06-4b9c-a964-3b36cd73b134.png)
![image](https://user-images.githubusercontent.com/37768911/200476873-02cb9447-8b94-484a-b6a1-9a8c22dc78a0.png)
![image](https://user-images.githubusercontent.com/37768911/200476900-9a34979e-ba29-49fc-bef0-2ac89be2aadc.png)
At this time, I even watch videos on youtube.
